Prn211CinemaSystem/Prn211CinemaSystem/Controllers/AdminController.cs
using BussinessObject.Models;
using CinemaSystemWebapp.Utils;
using DataAccess.Repository;
using DataAccess.Repository.impl;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace CinemaSystemWebapp.Controllers
{
    public class AdminController : Controller
    {
        IUserRepository _userRepository;
        ICategoryRepository _categoryRepository;
        IFilmRepository _filmRepository;
        IRoomRepository _roomRepository;
        IShowRepository _showRepository;
        ITicketRepository _ticketRepository;

        public AdminController()
        {
            _userRepository = new UserRepository();
            _categoryRepository = new CategoryRepository();
            _filmRepository = new FilmRepository();
            _roomRepository = new RoomRepository();
            _showRepository = new ShowRepository();
            _ticketRepository = new TicketRepository();
        }

        CinemaSystemContext dbcontext = new CinemaSystemContext();


        public User AdminUser { get; set; } = null!;

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var user = Authentication.GetUserByCookies(context.HttpContext.Request.Cookies);

            if (user is null || user.Role != (int)BussinessObject.Models.User.Roles.Admin)
            {
                context.Result = new RedirectResult("/");
            }

            AdminUser = user!;
        }

        public IActionResult Index(string? tab)
        {
            ViewBag.Categories = _categoryRepository.getListCategory();
            ViewBag.Films = _filmRepository.GetFilms();
            ViewBag.Orders = _ticketRepository.getAllTicket();

            ViewBag.ActiveTab = tab;

            return View(AdminUser);
        }

        [HttpPost]
        public IActionResult CreateShow(int id, float price, DateTime start, int room)
        {
            var film = _filmRepository.findById(id);
            var roomObj = _roomRepository.getRoomById(room);

            if (film is null || roomObj is null)
            {
                return RedirectToAction("Index", "Film", new { id = id, message = "Invalid film or room!" });
            }

            var show = new Show
            {
                FilmId = film.Id,
                RoomId = roomObj.Id,
                Start = start,
                End = start.AddMinutes(film.Length),
                TicketPrice = price
            };

            if (_showRepository.checkvalidShow(show))
            {
                return RedirectToAction("Index", "Film", new { id = id, message = "Show time is not valid!" });
            }

            _showRepository.addShow(show);

            return RedirectToAction("Index", "Film", new { id = id, message = "Create show successful!" });
        }

        [HttpPost]
        public IActionResult Category(int? id, string name, string description, string action)
        {
            switch (action)
            {
                case "create":
                    Category categoryAdd = new BussinessObject.Models.Category() { Name = name, Desc = description };
                    _categoryRepository.addCategory(categoryAdd);
                    break;
                case "edit":
                    if (id.HasValue)
                    {
                        Category categoryUpdate = new BussinessObject.Models.Category() { Id = id.Value, Name = name, Desc = description };
                        _categoryRepository.updateCategory(categoryUpdate);
                    }
                    break;
                case "delete":
                    if (id.HasValue)
                    {
                        Category categoryRemove = new BussinessObject.Models.Category() { Id = id.Value };
                        _categoryRepository.removeCategory(categoryRemove);

                    }
                    break;
                default:
                    break;
            }
            return RedirectToAction(nameof(Index), new { tab = "category" });
        }

        [HttpPost]
        public IActionResult Film(int? id, string name, string description, List<int>? categories, [FromForm(Name = "release-date")] DateTime? releaseDate, int? length, string action, IFormFile? image)
        {
            switch (action)
            {
                case "create":
                    if (image is not null)
                    {
                        var uploadPath = Path.Combine(Path.GetFullPath("wwwroot"), "assets");
                        using (var stream = image.OpenReadStream())
                        {
                            string filepath = $"/assets/{UploadFile.Upload(uploadPath, image.FileName, stream).FileName}";

                            dbcontext.Films.Add(new BussinessObject.Models.Film()
                            {
                                Name = name,
                                Desc = description,
                                Categories = dbcontext.Categories.Where(e => categories!.Contains(e.Id)).ToList(),
                                ReleaseDate = releaseDate!.Value,
                                Length = length!.Value,
                                ImageUrl = filepath
                            });

                            dbcontext.SaveChanges();
                        }
                    }
                    break;
                case "delete":
                    if (id.HasValue)
                    {
                        Film film = new BussinessObject.Models.Film() { Id = id.Value };
                        _filmRepository.deleteFilm(film);
                    }
                    break;
                default:
                    break;
            }

            return RedirectToAction(nameof(Index), new { tab = "film" });
        }
    }
}

Prn211CinemaSystem/Prn211CinemaSystem/Controllers/CategoryController.cs
using BussinessObject.Models;
using DataAccess.Repository;
using DataAccess.Repository.impl;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaSystemWebapp.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository categoryRepository = new CategoryRepository();

        public CinemaSystemContext dbcontext { get; set; } = new();

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            dbcontext.Dispose();
        }

        public IActionResult Index(int id)
        {
            Category category = categoryRepository.getCategoryWithFilms(id);
            return View(category);
        }
    }
}

Prn211CinemaSystem/Prn211CinemaSystem/Controllers/UserController.cs
using BussinessObject.Models;
using CinemaSystemWebapp.Utils;
using DataAccess.Repository;
using DataAccess.Repository.impl;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace CinemaSystemWebapp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository userRepository = new UserRepository();
        private readonly ITicketRepository ticketRepository = new TicketRepository();
        public IActionResult Setting()
        {
            var user = Authentication.GetUserByCookies(Request.Cookies);

            if (user is null)
                return RedirectToAction("Signin", "Home");

            return View(user);
        }
        [HttpPost]
        public IActionResult AddToCard(double money)
        {
            var user = Authentication.GetUserByCookies(Request.Cookies);
            if (user is null)
                return RedirectToAction("Signin", "Home");
            try
            {
                userRepository.AddToCard(user, money);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Signout", "Home");
            }
            return RedirectToAction(nameof(Setting));
        }
        public IActionResult Tickets()
        {
            var user = Authentication.GetUserByCookies(Request.Cookies);
            if (user is null)
                return RedirectToAction("Signin", "Home");
            using var db = new CinemaSystemContext();
            List<Ticket> list = ticketRepository.GetListTicketWithFullInformation();            
            return View(list.Where(e => e.UserId == user.Id).GroupBy(e => e.Show).ToList());
        }

        [HttpPost]
        public IActionResult ChangeInfo(string name, string email, IFormFile avatar)
        {
            var user = Authentication.GetUserByCookies(Request.Cookies);
            if (user is null)
                return RedirectToAction("Signin", "Home");
            string? newAvatar = null;
            if (avatar is not null)
            {
                var uploadPath = Path.Combine(Path.GetFullPath("wwwroot"), "assets");
                using (var stream = avatar.OpenReadStream())
                 newAvatar =   UploadFile.Upload(uploadPath, avatar.FileName, stream).FileName;
            }
            userRepository.UpdateUser(user, name, email, newAvatar);
            return RedirectToAction(nameof(Setting));
        }

        [HttpPost]
        public IActionResult ChangePassword([FromForm(Name = "old-password")] string oldPassword, [FromForm(Name = "confirm-password")] string confirmPassword, [FromForm(Name = "new-password")] string newPassword)
        {
            var user = Authentication.GetUserByCookies(Request.Cookies);
            if (user is null)
                return RedirectToAction("Signin", "Home");
            try
            {
                userRepository.ChangePassword(user, newPassword, confirmPassword, oldPassword);
            }catch(Exception ex)
            {
                return RedirectToAction("Signout", "Home");
            }
            return RedirectToAction(nameof(Setting));
        }
    }
}

Prn211CinemaSystem/Prn211CinemaSystem/Views/Shared/_Layout.cshtml
@{
    using CinemaSystemContext dbcontext = new();
    ViewBag.User = CinemaSystemWebapp.Utils.Authentication.GetUserByCookies(Context.Request.Cookies);
    ViewBag.Categories = dbcontext.Categories.ToList();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" href="assets/favicon.png">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/style.css">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.css" rel="stylesheet" />

    <!-- Recaptcha -->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script src="https://kit.fontawesome.com/de1d9009fe.js" crossorigin="anonymous"></script>

</head>

<body>

    <div class="hanime-nav-bar__overlay"></div>

    <header class="hanime-header d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
            <div class="hanime-header__nav-bar-btn">
                <i class="fa-solid fa-bars fa-2xl hanime-header__nav-bar-btn--icon"></i>
            </div>

            <a class="hanime-header__logo" style="width: 120px" asp-controller="Home" asp-action="Index">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 76 16" style="width: 100%">
                    <path style="fill: red;" d="M12,2V16H10a2,2,0,0,1-2-2V10H4v6H2a2,2,0,0,1-2-2V0H2a2,2,0,0,0,.59,1.41A2,2,0,0,0,4,2V6H8V0h2a2,2,0,0,0,.59,1.41A2,2,0,0,0,12,2Z" />
                    <path style="fill: #fff;" d="M24.59,1.41A2,2,0,0,1,24,0H16a2,2,0,0,0-1.41.59A2,2,0,0,0,14,2V14a2,2,0,0,0,2,2h2V10h4v4a2,2,0,0,0,2,2h2V2A2,2,0,0,1,24.59,1.41ZM22,4a2,2,0,0,1-2,2H18V4a2,2,0,0,1,2-2h0a2,2,0,0,1,2,2Z" />
                    <path style="fill: #fff;" d="M37,5a3.42,3.42,0,0,0-2.42-1H30a2,2,0,0,0-2,2h0v8h0a2,2,0,0,0,2,2h1V9h0a2,2,0,0,1,2-2h0a2,2,0,0,1,2,2h0v5a2,2,0,0,0,2,2h1V7.42A3.42,3.42,0,0,0,37,5Z" />
                    <rect style="fill: #fff;" x="40" width="4" height="4" rx="2" />
                    <rect style="fill: #fff;" x="40" y="5" width="4" height="11" rx="2" />
                    <path style="fill: #fff;" d="M63,7.42V16H62a2,2,0,0,1-2-2V9a2,2,0,0,0-4,0v7H55a2,2,0,0,1-2-2V9a2,2,0,0,0-4,0v7H48a2,2,0,0,1-2-2V6a2,2,0,0,1,2-2h4.58A3.41,3.41,0,0,1,54,4.29,2,2,0,0,1,55,4h4.58A3.41,3.41,0,0,1,63,7.42Z" />
                    <path style="fill: #fff;" d="M76,6.4a2.2,2.2,0,0,0-.81-1.69A2.87,2.87,0,0,0,73.25,4h-5.5A2.6,2.6,0,0,0,65,6.4v7.2a2.2,2.2,0,0,0,.81,1.69,2.87,2.87,0,0,0,1.94.71h5.5a2.87,2.87,0,0,0,1.94-.71A2.2,2.2,0,0,0,76,13.6H70.5a2.87,2.87,0,0,1-1.94-.71l-.13-.12a2.06,2.06,0,0,1-.42-.56,2.08,2.08,0,0,1-.26-1H76ZM71.88,8.8A1.3,1.3,0,0,1,70.5,7.6a1.39,1.39,0,0,1,2.75,0A1.3,1.3,0,0,1,71.88,8.8Z" />
                    <path style="fill: #ff765f;" d="M76,12.66c0,.06-.06.12-.16.17a.89.89,0,0,1-.38.07,1,1,0,0,1-.39-.07.92.92,0,0,0-.38-.07,1,1,0,0,0-.39.07.89.89,0,0,1-.38.07,1,1,0,0,1-.39-.07,1.07,1.07,0,0,0-.76,0,1,1,0,0,1-.39.07.89.89,0,0,1-.38-.07,1,1,0,0,0-.39-.07.92.92,0,0,0-.38.07,1,1,0,0,1-.39.07.89.89,0,0,1-.38-.07.89.89,0,0,0-.38-.07,1,1,0,0,0-.39.07,1,1,0,0,1-.39.07.89.89,0,0,1-.38-.07,1,1,0,0,0-.49-.06,2.06,2.06,0,0,1-.42-.56l.14,0a1,1,0,0,1,.39-.07.89.89,0,0,1,.38.07.89.89,0,0,0,.38.07,1,1,0,0,0,.39-.07,1,1,0,0,1,.39-.07.89.89,0,0,1,.38.07.89.89,0,0,0,.38.07,1,1,0,0,0,.39-.07.92.92,0,0,1,.38-.07,1,1,0,0,1,.39.07.89.89,0,0,0,.38.07,1,1,0,0,0,.39-.07,1.07,1.07,0,0,1,.76,0,1,1,0,0,0,.39.07.89.89,0,0,0,.38-.07,1,1,0,0,1,.77,0l.39.16.38.17C75.94,12.54,76,12.6,76,12.66Z" />
                </svg>
            </a>
        </div>

        <form class="hanime-header__search-bar" asp-action="Search" asp-controller="Home" method="get">
            <input type="text" name="q" value="@ViewBag.SearchQueryString" class="hanime-header__search-bar--input" placeholder="Search" />
            <button type="submit" class="hanime-header__search-bar--button">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </form>

        <div class="d-flex align-items-center">
            @if (ViewBag.User is not null)
            {
                <div class="hanime-header__account">
                    <a class="dropdown" role="button" href="#" data-mdb-toggle="dropdown" aria-expanded="false">
                        <img src="@ViewBag.User.AvatarUrl"
                             alt="avatar" width="30" height="30" class="rounded-circle" style="object-fit: cover; object-position: center;">
                    </a>

                    <div class="dropdown-menu dropdown-menu-dark p-2">
                        <a asp-action="Setting" asp-controller="User" class="dropdown-item rounded">
                            <i class="fa-solid fa-cog"></i>
                            <span>Setting</span>
                        </a>

                        @if (ViewBag.User?.Role == (int) BussinessObject.Models.User.Roles.Admin)
                        {
                            <a asp-controller="Admin" asp-action="Index" class="dropdown-item rounded">
                                <i class="fa-solid fa-crown"></i>
                                <span>Admin pages</span>
                            </a>
                        }

                        <hr class="dropdown-divider" />

                        <a asp-controller="Home" asp-action="Signout" class="dropdown-item rounded">
                            <i class="fa-solid fa-sign-out-alt"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </div>
            }
        </div>
    </header>

    <nav class="hanime-nav-bar" data-button-class="hanime-header__nav-bar-btn">
        <div class="hanime-nav-bar__nav-btn-and-logo d-flex align-items-center">
            <div class="hanime-header__nav-bar-btn">
                <i class="fa-solid fa-bars fa-2xl hanime-header__nav-bar-btn--icon"></i>
            </div>

            <a class="hanime-header__logo" style="width: 120px" asp-controller="Home" asp-action="Index">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 76 16" style="width: 100%">
                    <path style="fill: red;" d="M12,2V16H10a2,2,0,0,1-2-2V10H4v6H2a2,2,0,0,1-2-2V0H2a2,2,0,0,0,.59,1.41A2,2,0,0,0,4,2V6H8V0h2a2,2,0,0,0,.59,1.41A2,2,0,0,0,12,2Z" />
                    <path style="fill: #fff;" d="M24.59,1.41A2,2,0,0,1,24,0H16a2,2,0,0,0-1.41.59A2,2,0,0,0,14,2V14a2,2,0,0,0,2,2h2V10h4v4a2,2,0,0,0,2,2h2V2A2,2,0,0,1,24.59,1.41ZM22,4a2,2,0,0,1-2,2H18V4a2,2,0,0,1,2-2h0a2,2,0,0,1,2,2Z" />
                    <path style="fill: #fff;" d="M37,5a3.42,3.42,0,0,0-2.42-1H30a2,2,0,0,0-2,2h0v8h0a2,2,0,0,0,2,2h1V9h0a2,2,0,0,1,2-2h0a2,2,0,0,1,2,2h0v5a2,2,0,0,0,2,2h1V7.42A3.42,3.42,0,0,0,37,5Z" />
                    <rect style="fill: #fff;" x="40" width="4" height="4" rx="2" />
                    <rect style="fill: #fff;" x="40" y="5" width="4" height="11" rx="2" />
                    <path style="fill: #fff;" d="M63,7.42V16H62a2,2,0,0,1-2-2V9a2,2,0,0,0-4,0v7H55a2,2,0,0,1-2-2V9a2,2,0,0,0-4,0v7H48a2,2,0,0,1-2-2V6a2,2,0,0,1,2-2h4.58A3.41,3.41,0,0,1,54,4.29,2,2,0,0,1,55,4h4.58A3.41,3.41,0,0,1,63,7.42Z" />
                    <path style="fill: #fff;" d="M76,6.4a2.2,2.2,0,0,0-.81-1.69A2.87,2.87,0,0,0,73.25,4h-5.5A2.6,2.6,0,0,0,65,6.4v7.2a2.2,2.2,0,0,0,.81,1.69,2.87,2.87,0,0,0,1.94.71h5.5a2.87,2.87,0,0,0,1.94-.71A2.2,2.2,0,0,0,76,13.6H70.5a2.87,2.87,0,0,1-1.94-.71l-.13-.12a2.06,2.06,0,0,1-.42-.56,2.08,2.08,0,0,1-.26-1H76ZM71.88,8.8A1.3,1.3,0,0,1,70.5,7.6a1.39,1.39,0,0,1,2.75,0A1.3,1.3,0,0,1,71.88,8.8Z" />
                    <path style="fill: #ff765f;" d="M76,12.66c0,.06-.06.12-.16.17a.89.89,0,0,1-.38.07,1,1,0,0,1-.39-.07.92.92,0,0,0-.38-.07,1,1,0,0,0-.39.07.89.89,0,0,1-.38.07,1,1,0,0,1-.39-.07,1.07,1.07,0,0,0-.76,0,1,1,0,0,1-.39.07.89.89,0,0,1-.38-.07,1,1,0,0,0-.39-.07.92.92,0,0,0-.38.07,1,1,0,0,1-.39.07.89.89,0,0,1-.38-.07.89.89,0,0,0-.38-.07,1,1,0,0,0-.39.07,1,1,0,0,1-.39.07.89.89,0,0,1-.38-.07,1,1,0,0,0-.49-.06,2.06,2.06,0,0,1-.42-.56l.14,0a1,1,0,0,1,.39-.07.89.89,0,0,1,.38.07.89.89,0,0,0,.38.07,1,1,0,0,0,.39-.07,1,1,0,0,1,.39-.07.89.89,0,0,1,.38.07.89.89,0,0,0,.38.07,1,1,0,0,0,.39-.07.92.92,0,0,1,.38-.07,1,1,0,0,1,.39.07.89.89,0,0,0,.38.07,1,1,0,0,0,.39-.07,1.07,1.07,0,0,1,.76,0,1,1,0,0,0,.39.07.89.89,0,0,0,.38-.07,1,1,0,0,1,.77,0l.39.16.38.17C75.94,12.54,76,12.6,76,12.66Z" />
                </svg>
            </a>
        </div>

        <div class="hanime-nav-bar__choices">
            <a asp-controller="Home" asp-action="Index" class="hanime-nav-bar__link">
                <i class="fa-solid fa-home"></i>
                <span>Home</span>
            </a>

            <a class="hanime-nav-bar__link position-relative" onmousedown="toggleCategory()">
                <i class="fa-solid fa-list"></i>
                <span>Category</span>

                <i class="fa-solid fa-caret-down" style="position: absolute; right: 0;"></i>
            </a>
      
            <div class="hanime-nav-bar__category">
                @foreach (Category category in ViewBag.Categories)
                {
                    <a asp-controller="Category" asp-action="Index" asp-route-id="@category.Id" class="hanime-nav-bar__category--link">
                        @category.Name
                    </a>
                }
            </div>

            @if (ViewBag.User is not null)
            {
 
                <a asp-action="Tickets" asp-controller="User" class="hanime-nav-bar__link">
                    <i class="fa-solid fa-ticket"></i>
                    <span>My Tickets</span>
                </a>

                <a asp-action="Setting" asp-controller="User" class="hanime-nav-bar__link">
                    <i class="fa-solid fa-cog"></i>
                    <span>Setting</span>
                </a>

                @if (ViewBag.User?.Role == (int) BussinessObject.Models.User.Roles.Admin)
                {
                    <a asp-action="Index" asp-controller="Admin" class="hanime-nav-bar__link">
                        <i class="fa-solid fa-crown"></i>
                        <span>Admin pages</span>
                    </a>
                }
            }
            <hr>

            @if (ViewBag.User is null)
            {
                <a asp-controller="Home" asp-action="Signin" class="hanime-nav-bar__link">
                    <i class="fa-solid fa-right-to-bracket"></i>
                    <span>Login</span>
                </a>
                <a asp-controller="Home" asp-action="Signup" class="hanime-nav-bar__link">
                    <i class="fa-solid fa-user-plus"></i>
                    <span>Register</span>
                </a>
            }
            else
            {
                <a asp-controller="Home" asp-action="Signout" class="hanime-nav-bar__link">
                    <i class="fa-solid fa-sign-out-alt"></i>
                    <span>Logout</span>
                </a>
            }
        </div>
    </nav>

    <hr class="hanime-hr">
    <section class="hanime-body">
        @RenderBody()
    </section>

    <script src="/js/nav-bar.js"></script>

    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.js"></script>
</body>
</html>