Prn211CinemaSystem/Prn211CinemaSystem/Controllers/AdminController.cs
using BussinessObject.Models;
using CinemaSystemWebapp.Utils;
using DataAccess.Repository;
using DataAccess.Repository.impl;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace CinemaSystemWebapp.Controllers
{
    public class AdminController : Controller
    {
        IUserRepository _userRepository;
        ICategoryRepository _categoryRepository;
        IFilmRepository _filmRepository;
        IRoomRepository _roomRepository;
        IShowRepository _showRepository;
        ITicketRepository _ticketRepository;

        public AdminController()
        {
            _userRepository = new UserRepository();
            _categoryRepository = new CategoryRepository();
            _filmRepository = new FilmRepository();
            _roomRepository = new RoomRepository();
            _showRepository = new ShowRepository();
            _ticketRepository = new TicketRepository();
        }

        CinemaSystemContext dbcontext = new CinemaSystemContext();


        public User AdminUser { get; set; } = null!;

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var user = Authentication.GetUserByCookies(context.HttpContext.Request.Cookies);

            if (user is null || user.Role != (int)BussinessObject.Models.User.Roles.Admin)
            {
                context.Result = new RedirectResult("/");
            }

            AdminUser = user!;
        }

        public IActionResult Index(string? tab)
        {
            ViewBag.Categories = _categoryRepository.getListCategory();
            ViewBag.Films = _filmRepository.GetFilms();
            ViewBag.Orders = _ticketRepository.getAllTicket();

            ViewBag.ActiveTab = tab;

            return View(AdminUser);
        }

        [HttpPost]
        public IActionResult CreateShow(int id, float price, DateTime start, int room)
        {
            var film = _filmRepository.findById(id);
            var roomObj = _roomRepository.getRoomById(room);

            if (film is null || roomObj is null)
            {
                return RedirectToAction("Index", "Film", new { id = id, message = "Invalid film or room!" });
            }

            var show = new Show
            {
                FilmId = film.Id,
                RoomId = roomObj.Id,
                Start = start,
                End = start.AddMinutes(film.Length),
                TicketPrice = price
            };

            if (_showRepository.checkvalidShow(show))
            {
                return RedirectToAction("Index", "Film", new { id = id, message = "Show time is not valid!" });
            }

            _showRepository.addShow(show);

            return RedirectToAction("Index", "Film", new { id = id, message = "Create show successful!" });
        }

        [HttpPost]
        public IActionResult Category(int? id, string name, string description, string action)
        {
            switch (action)
            {
                case "create":
                    Category categoryAdd = new BussinessObject.Models.Category() { Name = name, Desc = description };
                    _categoryRepository.addCategory(categoryAdd);
                    break;
                case "edit":
                    if (id.HasValue)
                    {
                        Category categoryUpdate = new BussinessObject.Models.Category() { Id = id.Value, Name = name, Desc = description };
                        _categoryRepository.updateCategory(categoryUpdate);
                    }
                    break;
                case "delete":
                    if (id.HasValue)
                    {
                        Category categoryRemove = new BussinessObject.Models.Category() { Id = id.Value };
                        _categoryRepository.removeCategory(categoryRemove);

                    }
                    break;
                default:
                    break;
            }
            return RedirectToAction(nameof(Index), new { tab = "category" });
        }

        [HttpPost]
        public IActionResult Film(int? id, string name, string description, List<int>? categories, [FromForm(Name = "release-date")] DateTime? releaseDate, int? length, string action, IFormFile? image)
        {
            switch (action)
            {
                case "create":
                    if (image is not null)
                    {
                        var uploadPath = Path.Combine(Path.GetFullPath("wwwroot"), "assets");
                        using (var stream = image.OpenReadStream())
                        {
                            string filepath = $"/assets/{UploadFile.Upload(uploadPath, image.FileName, stream).FileName}";

                            dbcontext.Films.Add(new BussinessObject.Models.Film()
                            {
                                Name = name,
                                Desc = description,
                                Categories = dbcontext.Categories.Where(e => categories!.Contains(e.Id)).ToList(),
                                ReleaseDate = releaseDate!.Value,
                                Length = length!.Value,
                                ImageUrl = filepath
                            });

                            dbcontext.SaveChanges();
                        }
                    }
                    break;
                case "delete":
                    if (id.HasValue)
                    {
                        Film film = new BussinessObject.Models.Film() { Id = id.Value };
                        _filmRepository.deleteFilm(film);
                    }
                    break;
                default:
                    break;
            }

            return RedirectToAction(nameof(Index), new { tab = "film" });
        }
    }
}

Prn211CinemaSystem/Prn211CinemaSystem/Controllers/CategoryController.cs
using BussinessObject.Models;
using DataAccess.Repository;
using DataAccess.Repository.impl;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaSystemWebapp.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository categoryRepository = new CategoryRepository();

        public CinemaSystemContext dbcontext { get; set; } = new();

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            dbcontext.Dispose();
        }

        public IActionResult Index(int id)
        {
            Category category = categoryRepository.getCategoryWithFilms(id);
            return View(category);
        }
    }
}

Prn211CinemaSystem/Prn211CinemaSystem/Controllers/FilmController.cs
using BussinessObject.Models;
using DataAccess.Repository;
using DataAccess.Repository.impl;
using Microsoft.AspNetCore.Mvc;

namespace CinemaSystemWebapp.Controllers
{
    public class FilmController : Controller
    {
        IRoomRepository _roomRepository;
        IFilmRepository _filmRepository;

        public FilmController()
        {
            _roomRepository = new RoomRepository();
            _filmRepository = new FilmRepository();
        }
        public IActionResult Index(int id, string? message)
        {
            ViewBag.Message = message;
            ViewBag.Rooms = _roomRepository.getListRooms();
            Film film = _filmRepository.getFilmWithCategoriesShowsRoom(id);
            return View(film);
        }
    }
}

Prn211CinemaSystem/Prn211CinemaSystem/Controllers/ShowController.cs
using BussinessObject.Models;

using CinemaSystemWebapp.Utils;
using DataAccess.Repository.impl;
using DataAccess.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaSystemWebapp.Controllers
{
    public class ShowController : Controller
    {
        IShowRepository _showRepository;
        ITicketRepository _ticketRepository;
        public ShowController()
        {
            _showRepository = new ShowRepository();
            _ticketRepository = new TicketRepository();
        }

        public IActionResult Index(int id, string? message)
        {
            ViewBag.Message = message;
            Show show = _showRepository.getShowWithFilmRoomTickets(id);
            return View(show);
        }

        [HttpPost]
        public IActionResult BuyTicket(int id, int row, int col)
        {
            var user = Authentication.GetUserByCookies(Request.Cookies);

            if (user is null)
                return RedirectToAction("Signin", "Home");

            var show = _showRepository.getShowWithRoomTickets(id);

            if (show is null || show.Room?.Rows < row || show.Room?.Cols < col)
                return RedirectToAction(nameof(Index), new { id = id, message = "Invalid show or wrong seat!" });

            if (show.Tickets.Any(e => e.Row == row && e.Col == col))
                return RedirectToAction(nameof(Index), new { id = id, message = "Sorry! Your seat has been ordered!" });

            if (show.TicketPrice > user.Balance)
                return RedirectToAction(nameof(Index), new { id = id, message = "Your balance is not enough!" });

            string GenOTP()
            {
                var rand = new Random();
                return new string(Enumerable.Range(0, 6).Select(_ => (char)rand.Next('0', '9' + 1)).ToArray());
            }


            DateTime currentTime = DateTime.Now;
            Console.WriteLine(currentTime);
            Ticket ticket = new Ticket()
            {
                UserId = user.Id,
                ShowId = id,
                Row = row,
                Col = col,
                Date = currentTime,
                Otp = GenOTP()
            };
            Console.WriteLine(ticket.Date);



            _ticketRepository.addNewTicket(ticket);

            return RedirectToAction(nameof(Index), new { id = id, message = "Buy Ticket Success!" });
        }
    }
}

Prn211CinemaSystem/Prn211CinemaSystem/Views/Film/Index.cshtml
@model BussinessObject.Models.Film

@{
    ViewData["Title"] = Model.Name;
    ViewBag.User = CinemaSystemWebapp.Utils.Authentication.GetUserByCookies(Context.Request.Cookies);
}

@if (ViewBag.Message is not null)
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        @ViewBag.Message
        <button type="button" class="btn-close" onclick="this.parentNode.remove()"></button>
    </div>
}

<div class="container p-4 text-white-50">
    <div class="row">
        <div class="col-sm-12 col-md-6 d-flex justify-content-center flex-column">
            <img src="@Model.ImageUrl" class="img-fluid img-thumbnail" alt="">
        </div>

        <div class="col-sm-12 col-md-6 p-4 d-flex flex-column justify-content-center">
            <div class="row">
                <div class="col">Name</div>
                <div class="col text-truncate" data-mdb-toggle="tooltip" data-mdb-original-title="@Model.Name" />
                @Model.Name
            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col">Categories</div>

            <div class="col d-flex flex-wrap">

                @foreach (var category in Model.Categories)
                {
                    <a asp-controller="Category" asp-action="Index" asp-route-id="@category.Id" class="film-categories pe-2 pw-2">
                        @category.Name
                    </a>
                }

                @if (Model.Categories.Count == 0)
                {
                    <span>N/A</span>
                }

            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col">Length</div>
            <div class="col">@Model.Length</div>
        </div>
        <hr>

        <div class="row">
            <div class="col">ReleaseDate</div>
            <div class="col">@Model.ReleaseDate</div>
        </div>
        <hr>

        <div class="row">
            <h5>Description</h5>
            <p class="text-body">
                @Model.Desc
            </p>
        </div>
    </div>
</div>

<hr>

<div class="d-flex align-items-center">
    <h5>Shows</h5>

    @if (ViewBag.User?.Role == (int) BussinessObject.Models.User.Roles.Admin)
    {
        <div class="ms-2">
            <div class="p-0 m-0" asp-action="CreateShow" asp-controller="Admin" asp-route-id="@Model.Id" data-mdb-toggle="modal" data-mdb-target="#model-create-show">
                <div class="btn btn-dark">
                    <i class="fa fa-plus"></i>
                </div>
            </div>

            <div class="modal fade" tabindex="-1" aria-hidden="true" id="model-create-show">
                <form class="modal-dialog" asp-action="CreateShow" asp-controller="Admin">
                    <input type="hidden" name="id" value="@Model.Id" />

                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title text-dark">Create Show</h5>
                            <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body text-black-50">
                            <div class="form-outline mb-3">
                                <input type="number" class="form-control" name="price" value="0" min="0" required />
                                <label class="form-label">Ticket Price</label>
                            </div>

                            <div class="form-floating mb-3">
                                <input type="datetime-local" class="form-control" name="start" required />
                                <label class="form-label">Time</label>
                            </div>

                            <div class="form-floating mb-3">
                                <select name="room" class="form-select" required>
                                    @foreach (Room room in @ViewBag.Rooms)
                                    {
                                        <option value="@room.Id">
                                            @room.Name [@room.Rows - @room.Cols]
                                        </option>
                                    }
                                </select>
                                <label class="form-label">Room</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-mdb-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">OK</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    }
</div>

<div class="row p-2 pt-0">
    @{
        var currentDatetime = DateTime.Now;
    }
    @foreach (var show in Model.Shows.Where(e => e.End > currentDatetime).OrderBy(e => e.Start))
    {
        <a class="btn btn-sm p-0 m-2 w-100" asp-controller="Show" asp-action="Index" asp-route-id="@show.Id">
            <div class="row">
                <div class="col-12 col-sm-4 col-md-3">
                    <img class="img-fluid" style="object-fit: cover; object-position: center;"
                     src="@Model.ImageUrl"
                     alt="">
                </div>

                @{
                    var isAvailable = show.End > DateTime.Now;
                    var isPresent = show.Start < DateTime.Now && isAvailable;
                }

                <div class="col-12 col-sm-8 col-md-9 mb-2 d-flex flex-column justify-content-center">
                    <h6 class="text-truncate text-white m-0 mt-2">
                        @show.Room?.Name
                        @if (isPresent)
                        {
                            <span class="badge bg-success">Now</span>
                        }
                        else if (isAvailable)
                        {
                            <span class="badge bg-warning">Future</span>
                        }
                        else
                        {
                            <span class="badge bg-danger">Past</span>
                        }
                    </h6>

                    <strong class="mt-2">Start: @show.Start</strong>
                    <strong class="mt-2">End: @show.End</strong>
                </div>
            </div>
        </a>
    }
</div>